name: Notify on Telegram
on:
  pull_request:
    types: [opened, closed, reopened]
  issues:
    types: [opened, pinned, closed, reopened]
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Notify the commit on Telegram.
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.CHAT_ID }}
          token: ${{ secrets.BOT_TOKEN }}
          message: |
            ${{ github.event.name }}
            ${{ github.actor }}